//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_TRC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_test_daniel_chacon
    {
        public long id { get; set; }
        public string name { get; set; }
        public string second_name { get; set; }
        public string lastname { get; set; }
        public string second_lastname { get; set; }
        public System.DateTime birthdate { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> register_date { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
